on:
  pull_request:

jobs:
  plan:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref}}
          fetch-depth: 0

      # - name: Install tools using asdf
      #   uses: asdf-vm/actions/install@v3.0.2
      #
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.7.5"
          terraform_wrapper: false

      - name: Install Terramate
        uses: terramate-io/terramate-action@v1
        with:
          version: "0.10.2"

      - name: Configure AWS credentials
        # if: steps.list.outputs.stdout
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-west-1
          role-to-assume: arn:aws:iam::942123856864:role/github-oidc-provider-aws

      - name: Setup Infracost
        uses: infracost/actions/setup@v3
        with:
          api-key: ${{ secrets.INFRACOST_API_KEY }}

      - name: Create Terraform plan on changed stacks
        run: |
          terramate run --changed -- terraform init
          terramate run --changed -- terraform validate
          terramate run --changed -- terraform plan -out ./out.tfplan

      - name: Generate Infracost cost estimate baseline
        run: |
          terramate run --changed -- infracost breakdown \
            --path ./out.tfplan \
            --format=json \
            --usage-file infracost-usage-medium.yml \
            --out-file=./infracost-base.json

      - name: Post Infracost comment
        run: |
          terramate run --changed -- infracost comment github \
            --path=./infracost-base.json \
            --repo=$GITHUB_REPOSITORY \
            --github-token=${{github.token}} \
            --pull-request=${{github.event.pull_request.number}} \
            --behavior=new
